"""initial migration

Revision ID: 4025b05e021
Revises: None
Create Date: 2016-08-28 16:22:32.163849

"""

# revision identifiers, used by Alembic.
revision = '4025b05e021'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
